#mastlouis

CXX = gcc

CXXFLAGS = -g -Wall

TARGET = procAncestry testcalls

all:	$(TARGET)

clean: 
	rm procAncestry testCalls

procAncestry: procAncestry.c
	$(CXX) $(CXXFLAGS) -o procAncestry procAncestry.c

testcalls: testcalls.c
	$(CXX) $(CXXFLAGS) -o testcalls testcalls.c


